version: '3'
services:

  nginx:
    build: ./docker/nginx
    command: nginx -g "daemon off;"
    ports:
      - "${APP_PORT}:80"
    restart: unless-stopped
    networks:
      - skynet

  webserver:
    build: ./api
    volumes:
      - ./api:/var/www/html
    working_dir: /var/www/html
    command: php-fpm
    environment:
      APP_ENV: ${APP_ENV}
      APP_DEBUG: ${APP_DEBUG}
      DB_HOST: db
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    restart: unless-stopped
    networks:
      - skynet
      - skynet_back

  web:
    build:
      context: ./web
      dockerfile: Dockerfile.dev
    volumes:
      - ./web:/var/www/html
    restart: unless-stopped
    networks:
      - skynet

  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "${DB_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - skynet_back

networks:
  skynet:
  skynet_back:

volumes:
  db_data:
