version: '3'
services:
  nginx:
    image: ghcr.io/budgetbee/budgetbee/proxy:latest
    command: nginx -g "daemon off;"
    ports:
      - "8201:80"
    restart: unless-stopped
    networks:
      - skynet

  webserver:
    image: ghcr.io/budgetbee/budgetbee/api:latest
    working_dir: /var/www/html
    command: sh entrypoint.sh
    environment:
      DB_HOST: db
      DB_DATABASE: "budgetbee"
      DB_USERNAME: "budgetbee_user"
      DB_PASSWORD: "budgetbee_password"
    restart: unless-stopped
    networks:
      - skynet

  web:
    image: ghcr.io/budgetbee/budgetbee/web:latest
    restart: unless-stopped
    networks:
      - skynet

  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "budgetbee_password_root"
      MYSQL_DATABASE: "budgetbee"
      MYSQL_USER: "budgetbee_user"
      MYSQL_PASSWORD: "budgetbee_password"
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - skynet

networks:
  skynet:

volumes:
  db_data:
