version: '3'
services:
  nginx:
    image: nginx:1.25.1-alpine3.17-slim
    command: nginx -g "daemon off;"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "${API_PORT}:80"
    restart: unless-stopped
    networks:
      - skynet

  php:
    image: ghcr.io/budgetbee/budgetbee/api:latest
    working_dir: /var/www/html
    command: php-fpm
    environment:
      APP_ENV: ${APP_ENV}
      APP_DEBUG: ${APP_DEBUG}
      APP_LOCALE: es
      APP_FALLBACK_LOCALE: es
      DB_HOST: db
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      MEMCACHED_HOST: cache
      CACHE_DRIVER: memcached
    restart: unless-stopped
    networks:
      - skynet

  app:
    image: ghcr.io/budgetbee/budgetbee/web:latest
    ports:
      - "${APP_PORT}:3000"
    environment:
      REACT_APP_API_HOST: ${HOST}
      REACT_APP_API_PORT: ${API_PORT}
    restart: unless-stopped
    networks:
      - skynet

  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - skynet

  cache:
    image: memcached:1.6-alpine
    restart: unless-stopped
    networks:
      - skynet

networks:
  skynet:

volumes:
  db_data:
