name: Server Tests

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build the Docker image
      run: docker build ./api --file ./api/Dockerfile --build-arg APP_ENV=local --tag server

    - name: Run Docker container
      run: docker run -d --name mysql-container -e MYSQL_ROOT_PASSWORD=passwordTest mysql:8

    - name: Wait for MySQL container to start
      run: sleep 10

    - name: Run Docker container with server and link to MySQL
      run: docker run -d --name server-container --link mysql-container:mysql server

    - name: Wait for server container to start
      run: sleep 10

    - name: Execute migrations
      run: docker exec server-container php artisan migrate

    - name: Execute seeders
      run: docker exec server-container php artisan db:seed

    - name: Run tests
      run: docker exec server-container php artisan test
