name: Build and Push Docker Image

on:
  release:
    types: [published]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build the Docker image
      run: |
        docker build -t ghcr.io/budgetbee/budgetbee/api:${{ github.event.release.tag_name }} ./api
        docker build -t ghcr.io/budgetbee/budgetbee/app:${{ github.event.release.tag_name }} ./app
        docker tag ghcr.io/budgetbee/budgetbee/api:${{ github.event.release.tag_name }} ghcr.io/budgetbee/budgetbee/api:latest
        docker tag ghcr.io/budgetbee/budgetbee/app:${{ github.event.release.tag_name }} ghcr.io/budgetbee/budgetbee/app:latest

    - name: Login to ghcr.io
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push the Docker image to ghcr.io
      run: |
        docker push ghcr.io/budgetbee/budgetbee/api:${{ github.event.release.tag_name }}
        docker push ghcr.io/budgetbee/budgetbee/api:latest
        docker push ghcr.io/budgetbee/budgetbee/app:${{ github.event.release.tag_name }}
        docker push ghcr.io/budgetbee/budgetbee/app:latest
