name: Build and Push Docker Image

on:
  release:
    types: [published]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Determine tag prefix
      id: determine-tag-prefix
      run: echo ::set-output name=tag_prefix::${{ startsWith(github.event.release.tag_name, 'v') }}

    - name: Build the Docker image
      run: |
        docker build -t ghcr.io/budgetbee/budgetbee/api:${{ github.event.release.tag_name }} ./api
        docker build -t ghcr.io/budgetbee/budgetbee/app:${{ github.event.release.tag_name }} ./app
        if [[ "${{ steps.determine-tag-prefix.outputs.tag_prefix }}" == "true" ]]; then
          docker tag ghcr.io/budgetbee/budgetbee/api:${{ github.event.release.tag_name }} ghcr.io/budgetbee/budgetbee/api:latest
          docker tag ghcr.io/budgetbee/budgetbee/app:${{ github.event.release.tag_name }} ghcr.io/budgetbee/budgetbee/app:latest
        fi

    - name: Login to ghcr.io
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push the Docker image to ghcr.io
      run: |
        docker push ghcr.io/budgetbee/budgetbee/api:${{ github.event.release.tag_name }}
        if [[ "${{ steps.determine-tag-prefix.outputs.tag_prefix }}" == "true" ]]; then
          docker push ghcr.io/budgetbee/budgetbee/api:latest
        fi
        docker push ghcr.io/budgetbee/budgetbee/app:${{ github.event.release.tag_name }}
        if [[ "${{ steps.determine-tag-prefix.outputs.tag_prefix }}" == "true" ]]; then
          docker push ghcr.io/budgetbee/budgetbee/app:latest
        fi
